general {
    colors = true
    interval = 1

    color_good =     "#8cc85f"
    color_degraded = "#e3c78a"
    color_bad =      "#ff5454"

    # color_good =     "#b0b846"
    # color_degraded = "#e9b143"
    # color_bad =      "#f2594b"
}

order += "cpu_temperature 1"
order += "cpu_usage"
order += "memory"
order += "volume master"
order += "ethernet _first_"
order += "tztime local"

ethernet _first_ {
    format_up = "%interface: %ip"
    #format_up = "%interface: Connected"
    format_down = "%interface: Disconnected"
}

battery all {
    format = "%status %percentage %remaining"
}

disk "/" {
    format = "/: %used / %total"
}

disk "/home" {
    format = "/home: %used / %total"
}

memory {
    format = "RAM: %used/%total"
    threshold_degraded = "1G"
}

tztime local {
    format = "%a, %d/%m/%Y, %H:%M:%S"
}

volume master {
    format = "󰎈: %volume"
    format_muted = "󰎈: muted"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

cpu_usage {
    format = "CPU: %usage"
    max_threshold = "75"
}

cpu_temperature 1 {
    format = "T: %degrees°C"
    max_threshold = 60
    path = "/sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input"
}
